"""One-time historical data prep for the AE V3 experimental cascade (see
README's staged AE integration plan).

The experimental Kp/Dst models must never train on OBSERVED AE — only on
"predicted_ae", generated by running the already-trained, frozen AE 1h
model (models/ae/ae_1h.joblib) across history. This avoids a train/serve
mismatch: at live inference time there is no live AE feed, so the
cascade always supplies predicted_ae (never observed_ae) as the Kp/Dst
models' geomagnetic-activity feature — training must see the same thing.

Usage (from project root, with src/ on PYTHONPATH):
    PYTHONPATH=src venv/bin/python3 -m swdss.models.experimental
"""

import pandas as pd

from swdss.models.features import add_derived_physics_features, build_feature_frame
from swdss.models.predict import generate_predicted_ae
from swdss.models.registry import AE_FEATURE_VARIABLES, TRAINING_FEATURES_DIR


def build_experimental_features_csv() -> pd.DataFrame:
    ae_raw = pd.read_csv(TRAINING_FEATURES_DIR / "ae_analytics_features.csv")
    ae_raw["datetime"] = pd.to_datetime(ae_raw["datetime"])
    ae_raw = ae_raw.sort_values("datetime").set_index("datetime")

    base_df = ae_raw[AE_FEATURE_VARIABLES].copy()
    derived_cols = add_derived_physics_features(base_df)
    feature_vars = AE_FEATURE_VARIABLES + derived_cols
    frame, feature_columns = build_feature_frame(base_df, feature_vars)

    predicted_ae = generate_predicted_ae(frame)

    # analytics_features.csv already has an "ae" (observed) column merged
    # in from AE V2 — that must never reach the experimental models, only
    # predicted_ae may.
    analytics = pd.read_csv(TRAINING_FEATURES_DIR / "analytics_features.csv")
    analytics["datetime"] = pd.to_datetime(analytics["datetime"])
    analytics = analytics.sort_values("datetime").set_index("datetime").drop(columns=["ae"])

    experimental = analytics.copy()
    experimental["predicted_ae"] = predicted_ae.reindex(experimental.index)
    experimental = experimental.dropna(subset=["predicted_ae"])
    experimental = experimental.reset_index()

    out_path = TRAINING_FEATURES_DIR / "experimental_features.csv"
    experimental.to_csv(out_path, index=False)
    print(f"Wrote {out_path} ({len(experimental)} rows)")
    return experimental


if __name__ == "__main__":
    build_experimental_features_csv()
