"""Single source of truth for the prediction module.

Both train.py and predict.py import dataset configuration from here so the
training pipeline and the live inference pipeline can never drift apart.
"""

from dataclasses import dataclass
from pathlib import Path

from swdss.paths import MODELS_DIR, PROCESSED_DIR, TRAINING_FEATURES_DIR

HORIZONS = [1, 3, 6, 12, 24]

SOLAR_WIND_VARIABLES = ["speed", "density", "temperature"]
IMF_VARIABLES = ["bt", "bx_gsm", "by_gsm", "bz_gsm"]
KP_VARIABLES = ["kp"]
DST_VARIABLES = ["dst"]

# The Analytics "Combined Earth Analysis" predictor: forecasts Kp and Dst
# from the full Sun-Earth feature set (Solar Wind + IMF + Kp/Dst/AE lags),
# rather than each dataset's own narrower self-referential feature set.
# AE V2 (see README's staged AE plan): observed AE is now one more feature
# this production pipeline draws from — same lag/rolling/change mechanism
# already used for Kp/Dst, no new architecture. Predicted AE (the
# independent AE tab's model output) must never feed in here — only the
# historical/observed value, via the same static_variables + ffill path
# already used by the standalone "ae" dataset.
ANALYTICS_VARIABLES = ["kp", "dst"]
ANALYTICS_FEATURE_VARIABLES = [
    "speed",
    "density",
    "temperature",
    "bt",
    "bx_gsm",
    "by_gsm",
    "bz_gsm",
    "kp",
    "dst",
    "ae",
]

# AE (Auroral Electrojet) V1: an independent target parallel to Kp/Dst,
# driven by Solar Wind + IMF + derived physics only — deliberately no
# Kp/Dst inputs yet (see README's staged AE integration plan).
AE_VARIABLES = ["ae"]
AE_FEATURE_VARIABLES = [
    "speed",
    "density",
    "temperature",
    "bt",
    "bx_gsm",
    "by_gsm",
    "bz_gsm",
    "ae",
]

# AE V3 (research/experimental — see README's staged AE plan): a cascaded
# pipeline that feeds the frozen AE model's own OUTPUT ("predicted_ae")
# into Kp/Dst as an additional feature, instead of observed AE. Completely
# separate models/training data from the production "analytics" pipeline
# — this never touches or influences it. "predicted_ae" is generated by
# swdss.models.predict.generate_predicted_ae, using the same read-only,
# already-trained AE 1h model for both the one-time historical training
# column and every live prediction, so training and inference never see
# different generation logic (see swdss.models.experimental).
EXPERIMENTAL_VARIABLES = ["kp", "dst"]
EXPERIMENTAL_FEATURE_VARIABLES = [
    "speed",
    "density",
    "temperature",
    "bt",
    "bx_gsm",
    "by_gsm",
    "bz_gsm",
    "kp",
    "dst",
    "predicted_ae",
]

VARIABLE_LABELS = {
    "speed": "Speed",
    "density": "Density",
    "temperature": "Temperature",
    "bt": "Bt",
    "bx_gsm": "Bx",
    "by_gsm": "By",
    "bz_gsm": "Bz",
    "kp": "Kp",
    "dst": "Dst",
    "ae": "AE",
}

VARIABLE_UNITS = {
    "speed": "km/s",
    "density": "p/cm3",
    "temperature": "K",
    "bt": "nT",
    "bx_gsm": "nT",
    "by_gsm": "nT",
    "bz_gsm": "nT",
    "kp": "",
    "dst": "nT",
    "ae": "nT",
}


@dataclass(frozen=True)
class DatasetConfig:
    name: str
    training_csv: str
    variables: list
    processed_parquet: str = None
    raw_column_map: dict = None  # processed-parquet column -> training-feature column

    # Only needed when the engineered feature set spans more variables than
    # are actually predicted (e.g. Analytics predicts Kp/Dst but engineers
    # features from Solar Wind + IMF + Kp + Dst together). Defaults to
    # `variables` when unset.
    feature_variables: list = None

    # Only needed for multi-source datasets (no single processed_parquet of
    # their own): names of other DATASETS entries to merge live data from,
    # each contributing via its own raw_column_map.
    source_datasets: list = None

    # Per-variable divisor applied to the TRAINING data only, to correct a
    # unit mismatch against the live processed data (e.g. Kp is stored as
    # tenths in the OMNI-derived training CSVs but as natural 0-9 values in
    # the live NOAA feed).
    scale_factors: dict = None

    # Variables with no continuously-updating live feed (e.g. AE, which
    # NOAA doesn't publish in real time — only a historical/periodically
    # refreshed file exists). Live inference forward-fills the last known
    # value for these instead of time-interpolating, and actual-value
    # resolution for completed jobs must look at the raw source directly
    # rather than ever treating that forward-filled value as ground truth
    # (see predict.resolve_static_actual).
    static_variables: list = None


DATASETS = {
    "solar_wind": DatasetConfig(
        name="solar_wind",
        training_csv=str(TRAINING_FEATURES_DIR / "solar_wind_features.csv"),
        variables=SOLAR_WIND_VARIABLES,
        processed_parquet=str(PROCESSED_DIR / "solar_wind" / "solar_wind_processed.parquet"),
        raw_column_map={
            "solar_wind_speed": "speed",
            "proton_density": "density",
            "temperature": "temperature",
        },
    ),
    "imf": DatasetConfig(
        name="imf",
        training_csv=str(TRAINING_FEATURES_DIR / "imf_features.csv"),
        variables=IMF_VARIABLES,
        processed_parquet=str(PROCESSED_DIR / "imf" / "imf_processed.parquet"),
        raw_column_map={
            "bt": "bt",
            "bx": "bx_gsm",
            "by": "by_gsm",
            "bz": "bz_gsm",
        },
    ),
    "kp": DatasetConfig(
        name="kp",
        training_csv=str(TRAINING_FEATURES_DIR / "kp_features.csv"),
        variables=KP_VARIABLES,
        processed_parquet=str(PROCESSED_DIR / "kp" / "kp_processed.parquet"),
        raw_column_map={"kp": "kp"},
        scale_factors={"kp": 10.0},
    ),
    "dst": DatasetConfig(
        name="dst",
        training_csv=str(TRAINING_FEATURES_DIR / "dst_features.csv"),
        variables=DST_VARIABLES,
        processed_parquet=str(PROCESSED_DIR / "dst" / "dst_processed.parquet"),
        raw_column_map={"dst": "dst"},
    ),
    "analytics": DatasetConfig(
        name="analytics",
        training_csv=str(TRAINING_FEATURES_DIR / "analytics_features.csv"),
        variables=ANALYTICS_VARIABLES,
        feature_variables=ANALYTICS_FEATURE_VARIABLES,
        # "ae" reuses the same DATASETS["ae"] source (its historical
        # parquet) that the standalone AE predictor reads from — there is
        # no separate live AE feed to merge in here.
        source_datasets=["solar_wind", "imf", "kp", "dst", "ae"],
        scale_factors={"kp": 10.0},
        static_variables=["ae"],
    ),
    "ae": DatasetConfig(
        name="ae",
        training_csv=str(TRAINING_FEATURES_DIR / "ae_analytics_features.csv"),
        variables=AE_VARIABLES,
        processed_parquet=str(PROCESSED_DIR / "ae" / "ae_processed.parquet"),
        raw_column_map={"ae": "ae"},
        feature_variables=AE_FEATURE_VARIABLES,
        # "ae" is listed as its own source too — NOAA has no live AE feed,
        # so its "live" value comes from this same historical parquet,
        # forward-filled (see static_variables) rather than truly updating
        # minute to minute like Solar Wind/IMF do.
        source_datasets=["solar_wind", "imf", "ae"],
        static_variables=["ae"],
    ),
    "experimental": DatasetConfig(
        name="experimental",
        training_csv=str(TRAINING_FEATURES_DIR / "experimental_features.csv"),
        variables=EXPERIMENTAL_VARIABLES,
        feature_variables=EXPERIMENTAL_FEATURE_VARIABLES,
        # "predicted_ae" is NOT one of these — it has no stored source at
        # all (no parquet, no raw_column_map). It's synthesized live by
        # running the frozen AE model (see predict.generate_predicted_ae
        # and predict.load_live_features's "experimental" branch).
        source_datasets=["solar_wind", "imf", "kp", "dst"],
        scale_factors={"kp": 10.0},
    ),
}


def owning_source_config(dataset: str, variable: str) -> DatasetConfig:
    """For multi-source datasets (e.g. "analytics"), returns the actual
    DATASETS entry that owns live data for `variable` (e.g. the "kp"
    config for variable="kp"), so live lookups can use its own
    processed_parquet + raw_column_map. For single-source datasets,
    just returns their own config.
    """
    config = DATASETS[dataset]
    if not config.source_datasets:
        return config
    for source_name in config.source_datasets:
        source_config = DATASETS[source_name]
        if variable in (source_config.raw_column_map or {}).values():
            return source_config
    raise KeyError(f"No source dataset owns variable '{variable}' for '{dataset}'")


def raw_column_for(dataset: str, variable: str) -> str:
    """Inverse of raw_column_map: given a training-feature variable name
    (e.g. "speed"), returns the matching live processed-parquet column
    (e.g. "solar_wind_speed"). Resolves through the owning source dataset
    for multi-source datasets.
    """
    config = owning_source_config(dataset, variable)
    for raw_col, training_col in (config.raw_column_map or {}).items():
        if training_col == variable:
            return raw_col
    raise KeyError(f"No raw column mapped to variable '{variable}' in dataset '{dataset}'")


def model_dir(dataset: str) -> Path:
    path = Path(MODELS_DIR) / dataset
    path.mkdir(parents=True, exist_ok=True)
    return path


def model_path(dataset: str, variable: str, horizon: int) -> Path:
    return model_dir(dataset) / f"{variable}_{horizon}h.joblib"


def metrics_path(dataset: str) -> Path:
    return model_dir(dataset) / "metrics.json"


def kp_interval_model_path(dataset: str = "analytics") -> Path:
    """Kp on the Analytics page follows NOAA's real 3-hour publishing
    cadence instead of an arbitrary hourly horizon, so it gets one model
    (not five) stored outside the normal {variable}_{horizon}h.joblib
    convention.
    """
    return model_dir(dataset) / "kp_interval.joblib"
