"""Rule-based forecast driver ranking and explanation — connects the
Physics Engine's live readings to the Kp/Dst/AE forecasts they drive
(the Forecast tab and Physics tab were, until now, isolated views).

Every ranking is a deterministic severity score against thresholds
already established elsewhere in this codebase (swdss.models.
physics_interpretation's VBz/AE bands, swdss.engine.alerts' southward-
duration/magnetopause-compression thresholds, swdss.physics.*'s own
documented expected ranges) — nothing here is fitted, inferred, or
generated by a model.

Real per-forecast SHAP attribution against the deployed model — not an
approximation of it — is layered on top via attach_shap_attribution(),
reusing the same Shapley-value machinery already exposed on-demand in
each job dialog's "Why did the model predict this?" panel (see
swdss.models.explainability.explain_prediction). It is attached
alongside, not blended into, the rule-based ranking above: the
physics-driver sentence stays a deterministic account of upstream
conditions, while the "shap" key on each explanation carries the
model's own statistically exact feature attribution for the current
prediction. Best-effort — a SHAP failure (e.g. not enough live feature
history yet) never blocks or discards the rule-based explanation.
"""

import math

from swdss.models.explainability import explain_prediction

TARGET_VARIABLES = ("kp", "dst", "ae")

TREND_VERBS = {
    "Increasing": "increase",
    "Decreasing": "decrease",
    "Stable": "remain stable",
    "More Southward": "increase",
    "Less Southward": "decrease",
}


def _driver_candidates(physics: dict) -> list:
    """Returns [(name, severity 0-3, detail_text), ...] for every physics
    quantity that can plausibly explain a Kp/Dst/AE forecast, scored
    against thresholds already used elsewhere in this app.
    """
    candidates = []

    clock_label = physics.get("clock_angle_label")
    clock_severity = {"Southward": 3, "Southward-leaning": 2, "Northward-leaning": 1, "Northward": 0}.get(clock_label, 0)
    if clock_severity > 0:
        angle = physics.get("clock_angle_deg")
        candidates.append(("Southward IMF", clock_severity, f"clock angle {angle:.0f}° ({clock_label})" if angle is not None else clock_label))

    coupling_label = physics.get("coupling_label")
    coupling_severity = {"Strong": 3, "Moderate": 2, "Weak": 0}.get(coupling_label, 0)
    if coupling_severity > 0:
        newell = physics.get("newell_coupling")
        candidates.append(("Elevated Newell Coupling", coupling_severity, f"Newell coupling {newell:.0f} ({coupling_label})" if newell is not None else coupling_label))

    dp_label = physics.get("dynamic_pressure_label")
    dp_severity = {"High (shock/CME sheath likely)": 3, "Elevated": 2, "Typical": 0}.get(dp_label, 0)
    if dp_severity > 0:
        dp = physics.get("dynamic_pressure")
        candidates.append(("Increasing Dynamic Pressure", dp_severity, f"dynamic pressure {dp:.2f} nPa ({dp_label})" if dp is not None else dp_label))

    vbz = physics.get("vbz")
    if vbz is not None and vbz < 0:
        if vbz <= -3000:
            candidates.append(("High VBz", 3, f"VBz {vbz:.0f} nT·km/s (strong coupling)"))
        elif vbz <= -1000:
            candidates.append(("High VBz", 2, f"VBz {vbz:.0f} nT·km/s (moderate coupling)"))
        else:
            candidates.append(("High VBz", 1, f"VBz {vbz:.0f} nT·km/s (weak coupling)"))

    ey = physics.get("ey")
    if ey is not None and ey > 0:
        if ey > 10:
            candidates.append(("High Ey", 3, f"Ey {ey:.2f} mV/m"))
        elif ey > 5:
            candidates.append(("High Ey", 2, f"Ey {ey:.2f} mV/m"))
        else:
            candidates.append(("High Ey", 1, f"Ey {ey:.2f} mV/m"))

    southward_hr = physics.get("southward_duration_hr") or 0
    if southward_hr >= 6:
        candidates.append(("Sustained Southward Duration", 3, f"{southward_hr:.0f}h continuous southward IMF"))
    elif southward_hr >= 3:
        candidates.append(("Sustained Southward Duration", 2, f"{southward_hr:.0f}h continuous southward IMF"))
    elif southward_hr > 0:
        candidates.append(("Southward Duration", 1, f"{southward_hr:.0f}h continuous southward IMF"))

    akasofu = physics.get("akasofu_epsilon_watts")
    if akasofu is not None and akasofu > 0:
        magnitude = math.log10(akasofu)
        if magnitude >= 11:
            candidates.append(("High Akasofu ε (Energy Input)", 3, f"Akasofu ε {akasofu:.2e} W"))
        elif magnitude >= 10:
            candidates.append(("Elevated Akasofu ε (Energy Input)", 2, f"Akasofu ε {akasofu:.2e} W"))

    compression = physics.get("estimated_compression_pct")
    if compression is not None:
        if compression >= 15:
            candidates.append(("Strong Magnetopause Compression", 3, f"{compression:.0f}% above nominal standoff"))
        elif compression >= 8:
            candidates.append(("Magnetopause Compression", 2, f"{compression:.0f}% above nominal standoff"))

    return candidates


def _rank(candidates: list) -> dict:
    ranked = sorted(candidates, key=lambda c: -c[1])
    result = {"primary": None, "secondary": None, "supporting": None, "detail": []}
    labels = ["primary", "secondary", "supporting"]
    for i, (name, _severity, detail) in enumerate(ranked[:3]):
        result[labels[i]] = name
        result["detail"].append(f"{name} ({detail})")
    return result


def build_explanations(physics: dict, forecast_entries: dict) -> dict:
    """`forecast_entries`: {"kp": entry, "dst": entry, "ae": entry} — the
    headline forecast entries, used only for each variable's own trend
    word (Increasing/Decreasing/Stable/More-or-Less Southward) to phrase
    the explanation sentence; the driver ranking itself comes entirely
    from `physics`, computed once and shared across all three targets
    (the same upstream conditions drive all of them).

    Returns {"kp": {...}, "dst": {...}, "ae": {...}}, each a dict with
    primary/secondary/supporting driver names, a detail list, and a
    human-readable sentence.
    """
    candidates = _driver_candidates(physics)
    ranked_once = _rank(candidates)

    explanations = {}
    labels = {"kp": "Kp", "dst": "Dst", "ae": "AE"}
    for variable in TARGET_VARIABLES:
        entry = forecast_entries.get(variable)
        trend = (entry or {}).get("trend", "Stable")
        verb = TREND_VERBS.get(trend, "change")
        ranked = dict(ranked_once)
        ranked["detail"] = list(ranked_once["detail"])

        if ranked["primary"]:
            sentence = f"Expected {labels[variable]} {verb} primarily driven by {ranked['primary'].lower()}"
            if ranked["secondary"]:
                sentence += f", with {ranked['secondary'].lower()} as a secondary factor"
            sentence += "."
        else:
            sentence = f"Expected {labels[variable]} {verb} — no dominant physics driver identified (quiet upstream conditions)."
        ranked["sentence"] = sentence
        explanations[variable] = ranked
    return explanations


def attach_shap_attribution(explanations: dict, headline_entries: dict) -> dict:
    """Augments each variable's rule-based explanation (already built by
    build_explanations) with genuine per-forecast SHAP attribution
    against the deployed model, so the Forecast Explanation Engine
    banner carries real model attribution without a user needing to
    open a job dialog to see it.

    `headline_entries` supplies the (dataset, variable, horizon) each
    entry was actually built from — the exact identifiers
    explain_prediction needs to load the right model and feature row.
    Mutates and returns `explanations`; best-effort per variable, so a
    SHAP failure for one target (e.g. not enough live feature history
    yet) leaves the others and the rule-based ranking untouched.
    """
    for variable, entry in headline_entries.items():
        if entry is None or variable not in explanations:
            continue
        try:
            result = explain_prediction(entry["dataset"], entry["variable"], entry["horizon"])
        except Exception:
            continue
        if result["method"] == "unavailable" or not result["contributions"]:
            continue
        explanations[variable]["shap"] = {
            "method": result["method"],
            "model_name": result["model_name"],
            "top_drivers": [
                {"feature": feat, "value": val, "contribution": contrib}
                for feat, val, contrib in result["contributions"][:5]
            ],
        }
    return explanations
